### ISSUE TITLE
SyntaxError on python 3.4

### ISSUE THREAD

**Issue by samupl** [dcramer/django-devserver#109]
```
/home/js/.virtualenvs/ppm/bin/python /home/js/git/ppm/manage.py runserver 8000
Traceback (most recent call last):
  File "/home/js/git/ppm/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/js/.virtualenvs/ppm/lib64/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/js/.virtualenvs/ppm/lib64/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/home/js/.virtualenvs/ppm/lib64/python3.4/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/js/.virtualenvs/ppm/lib64/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/js/.virtualenvs/ppm/lib64/python3.4/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1467, in exec_module
  File "<frozen importlib._bootstrap>", line 1572, in get_code
  File "<frozen importlib._bootstrap>", line 1532, in source_to_code
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/js/.virtualenvs/ppm/lib64/python3.4/site-packages/devserver/models.py", line 20
    raise exceptions.ImproperlyConfigured, '%s isn\'t a devserver module' % path
                                         ^
SyntaxError: invalid syntax
```

**Comment by rm--** [comment]
There is a still a PR #75 to fix this.
